In [1]:
import torch
from torch.autograd import Variable # torch 中 Variable 模块

# 先生鸡蛋
tensor = torch.FloatTensor([[1,2],[3,4]])
# 把鸡蛋放到篮子里, requires_grad是参不参与误差反向传播, 要不要计算梯度
variable = Variable(tensor, requires_grad=True)
print(tensor)
print(variable)

tensor([[1., 2.],
        [3., 4.]])
tensor([[1., 2.],
        [3., 4.]], requires_grad=True)


# Variable 计算, 梯度

我们再对比一下 tensor 的计算和 variable 的计算.

In [3]:
print("tensor =", tensor)
t_out = torch.mean(tensor*tensor)       # x^2
v_out = torch.mean(variable*variable)   # x^2print(t_out)
print(v_out)    # 7.5

tensor = tensor([[1., 2.],
        [3., 4.]])
tensor(7.5000, grad_fn=<MeanBackward1>)


但是时刻记住,**Variable**计算时, 它在背景幕布后面一步步默默地搭建着一个庞大的系统, 叫做计算图,**computational graph.** 这个图是用来干嘛的? 原来是将所有的计算步骤 (节点) 都连接起来, 最后进行误差反向传递的时候, 一次性将所有 variable 里面的修改幅度 (梯度) 都计算出来, 而**tensor**就没有这个能力啦.

In [4]:
v_out.backward()    # 模拟 v_out 的误差反向传递
print(variable.grad)    # 初始 Variable 的梯度

tensor([[0.5000, 1.0000],
        [1.5000, 2.0000]])


### 获取 Variable 里面的数据

In [5]:
print(variable)     #  Variable 形式
print(variable.data)    # tensor 形式
print(variable.data.numpy())    # numpy 形式

tensor([[1., 2.],
        [3., 4.]], requires_grad=True)
tensor([[1., 2.],
        [3., 4.]])
[[1. 2.]
 [3. 4.]]
