1.Python中 copy, deepcopy 的区别及原因
-----------------------------------

参考链接：https://iaman.actor/blog/2016/04/17/copy-in-python

Python 的 copy 模块中的 copy() method 其实是与 deep copy 相对的 shallow copy。copy.copy(object) 就等于是对 object 做了 shallow copy。

* 对于简单的object，用shallow copy和deep copy没区别:

In [1]:
import copy

origin = 1
cop1 = copy.copy(origin)
cop2 = copy.deepcopy(origin)
origin = 2
print(origin)
print(cop1)
print(cop2)
#cop1 和 cop2 都不会随着 origin 改变自己的值
print(cop1 == cop2)
print(cop1 is cop2)

2
1
1
True
True


* 复杂的object，如list中套着list的情况，shallow copy中的子list，并未从原object真的「独立」出来。

也就是说，如果你改变原 object 的子 list 中的一个元素，你的 copy 就会跟着一起变。这跟我们直觉上对「复制」的理解不同。

In [2]:
origin = [1, 2, [3, 4]]
#origin 里边有三个元素：1， 2，[3, 4]
cop1 = copy.copy(origin)
cop2 = copy.deepcopy(origin)
print(cop1 == cop2)
print(cop1 is cop2)

True
False


In [3]:
origin[2][0] = "key!"
origin

[1, 2, ['key!', 4]]

In [4]:
# 可以看到cop1，也就是shallow copy跟着origin改变了。
cop1

[1, 2, ['key!', 4]]

In [5]:
# 而cop2，也就是 deep copy 并没有变。
cop2

[1, 2, [3, 4]]

* 似乎 deep copy 更加符合我们对「复制」的直觉定义: 一旦复制出来了，就应该是独立的了。如果我们想要的是一个字面意义的「copy」，那就直接用 deep_copy 即可。

2.Numpy中random模块
------------------------------------

2.1 randint用法
-----------------------

In [7]:
import numpy as np
pact = np.random.randint(3)
pact

0

2.2 numpy.random.randn()用法
------------------------------
参考资料：https://blog.csdn.net/u012149181/article/details/78913167

numpy.random.rand(d0,d1,…,dn)
* rand函数根据给定维度生成[0,1)之间的数据，包含0，不包含1
* dn表格每个维度
* 返回值为指定维度的array

In [8]:
# 默认为1
np.random.rand()

0.6919750647407069

In [9]:
np.random.rand(4,2)

array([[0.62004829, 0.79216503],
       [0.87915653, 0.20048038],
       [0.05545771, 0.36665215],
       [0.13891378, 0.72844213]])

In [10]:
np.random.rand(4,3,2) # shape: 4*3*2

array([[[0.90270884, 0.42183535],
        [0.20989792, 0.96037623],
        [0.74883241, 0.09403585]],

       [[0.44358378, 0.23728944],
        [0.4164707 , 0.00405981],
        [0.20775486, 0.03861572]],

       [[0.85445611, 0.18073666],
        [0.45110635, 0.97149011],
        [0.38449769, 0.73254881]],

       [[0.33341161, 0.92838165],
        [0.65107586, 0.75502876],
        [0.89980264, 0.9673063 ]]])

2.3 numpy.random.randn()
-----------------------------

numpy.random.randn(d0,d1,…,dn)

* randn函数返回一个或一组样本，具有标准正态分布。
* dn表格每个维度
* 返回值为指定维度的array

### 标准正态分布介绍

* 标准正态分布—-standard normal distribution
* 标准正态分布又称为u分布，是以0为均值、以1为标准差的正态分布，记为N（0，1）。

In [11]:
np.random.randn() # 当没有参数时，返回单个数据

-0.6224122577805592

In [12]:
np.random.randn(2,4)

array([[-0.4764618 , -1.04419602, -0.45465733, -0.30609242],
       [ 0.04493374,  0.05797635,  0.58231442,  1.78774517]])

In [13]:
np.random.randn(4,3,2)

array([[[-0.46742296,  0.99846852],
        [-0.14194394,  1.68703126],
        [-1.8244719 , -0.19907507]],

       [[-1.76740272, -1.81445106],
        [-1.36233662, -1.31708152],
        [ 0.56111711,  0.45146996]],

       [[-1.28032424, -0.84990671],
        [-0.15982417,  1.1888378 ],
        [-0.20539579,  0.85418602]],

       [[ 0.16330537, -1.64851441],
        [-1.04031596,  0.07329011],
        [ 1.33111313, -0.26899331]]])

2.4 numpy.random.randint()
-------------------------------
numpy.random.randint(low, high=None, size=None, dtype=’l’)

* 返回随机整数，范围区间为[low,high），包含low，不包含high
* 参数：low为最小值，high为最大值，size为数组维度大小，dtype为数据类型，默认的数据类型是np.int
* high没有填写时，默认生成随机数的范围是[0，low)

In [14]:
# 下面指定了为size
np.random.randint(1,size=5) # 返回[0,1)之间的整数，所以只有0

array([0, 0, 0, 0, 0])

In [15]:
# 下面指定了low与high
np.random.randint(1,5) # 返回1个[1,5)时间的随机整数

2

In [16]:
np.random.randint(-5,5,size=(2,2))

array([[-2, -1],
       [-5,  0]])

2.5 numpy.random.random_integers
-------------------------------------
numpy.random.random_integers(low, high=None, size=None)

* 返回随机整数，范围区间为[low,high]，包含low和high
* 参数：low为最小值，high为最大值，size为数组维度大小
* high没有填写时，默认生成随机数的范围是[1，low]


该函数在最新的numpy版本中已被替代，建议使用** randint **函数

In [18]:
np.random.random_integers(1,size=5)
np.random.randint(1,size=5)

D:\Anaconda\lib\site-packages\ipykernel_launcher.py:1: DeprecationWarning: This function is deprecated. Please call randint(1, 1 + 1) instead
  """Entry point for launching an IPython kernel.


array([0, 0, 0, 0, 0])

2.6 生成[0,1)之间的浮点数
---------------------------------------

* numpy.random.random_sample(size=None)
* numpy.random.random(size=None)
* numpy.random.ranf(size=None)
* numpy.random.sample(size=None)

In [19]:
print('-----------random_sample--------------')
print(np.random.random_sample(size=(2,2)))
print('-----------random--------------')
print(np.random.random(size=(2,2)))
print('-----------ranf--------------')
print(np.random.ranf(size=(2,2)))
print('-----------sample--------------')
print(np.random.sample(size=(2,2)))

-----------random_sample--------------
[[0.12004985 0.53756097]
 [0.46279992 0.631226  ]]
-----------random--------------
[[0.20588875 0.30619765]
 [0.4719633  0.92701338]]
-----------ranf--------------
[[0.68391441 0.48519121]
 [0.89043706 0.85149536]]
-----------sample--------------
[[0.29774079 0.456007  ]
 [0.88863084 0.27216937]]


2.7 numpy.random.choice()
--------------------------

numpy.random.choice(a, size=None, replace=True, p=None)

* 从给定的一维数组中生成随机数
* 参数： a为一维数组类似数据或整数；size为数组维度；p为数组中的数据出现的概率
* a为整数时，对应的一维数组为np.arange(a)

In [20]:
np.random.choice(5,3)

array([4, 3, 0])

In [21]:
np.random.choice(5, 3, replace=False)
# 当replace为False时，生成的随机数不能有重复的数值

array([4, 1, 2])

In [22]:
np.random.choice(5,size=(3,2))

array([[3, 0],
       [2, 2],
       [0, 2]])

In [23]:
demo_list = ['lenovo', 'sansumg','moto','xiaomi', 'iphone']
np.random.choice(demo_list,size=(3,3))

array([['xiaomi', 'lenovo', 'iphone'],
       ['lenovo', 'iphone', 'xiaomi'],
       ['xiaomi', 'sansumg', 'lenovo']], dtype='<U7')

* 参数p的长度与参数a的长度需要一致；
* 参数p为概率，p里的数据之和应为1；

In [25]:
demo_list = ['lenovo', 'sansumg','moto','xiaomi', 'iphone']
np.random.choice(demo_list,size=(3,3), p=[0.1,0.6,0.1,0.1,0.1])

array([['sansumg', 'sansumg', 'sansumg'],
       ['iphone', 'sansumg', 'sansumg'],
       ['sansumg', 'sansumg', 'sansumg']], dtype='<U7')

2.8 numpy.random.seed()
------------------------------
* np.random.seed()的作用：使得随机数据可预测。
* 当我们设置相同的seed，每次生成的随机数相同。**如果不设置seed，则每次会生成不同的随机数**。

In [26]:
np.random.seed(0)
np.random.rand(5)

array([0.5488135 , 0.71518937, 0.60276338, 0.54488318, 0.4236548 ])

In [27]:
np.random.seed(1676)
np.random.rand(5)

array([0.39983389, 0.29426895, 0.89541728, 0.71807369, 0.3531823 ])

In [29]:
np.random.seed(1676)
np.random.rand(5)

array([0.39983389, 0.29426895, 0.89541728, 0.71807369, 0.3531823 ])